### ISSUE TITLE
Duplicities in signatory list

### ISSUE THREAD

**Issue by daliborjelinek** [bppdddqqqq/gallopy-petition#5]
![image](https://user-images.githubusercontent.com/14929823/234523023-36718f17-cd04-4b6f-a7b4-c9bd8640a508.png)

Some records are displayed multipe times.

**Comment by bppdddqqqq** [comment]
fixed, solution is on the front-end. Front-end now checks for duplicate items and doesn't  add them. this solution is 99.99% reliant
